### ISSUE TITLE
At Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by lqlau** [mattsawyer77/atom-perforce#68]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.0-beta4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-perforce](https://github.com/mattsawyer77/atom-perforce) package, v1.7.6
### Stack Trace

Failed to activate the atom-perforce package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at Object.setupEnvironment (C:\Users\MyUser\.atom\packages\atom-perforce\lib\atom-perforce.js:147:40)
    at execP4Command (C:\Users\MyUser\.atom\packages\atom-perforce\lib\atom-perforce.js:44:64)
    at Object.showClientName (C:\Users\MyUser\.atom\packages\atom-perforce\lib\atom-perforce.js:556:13)
    at C:\Users\MyUser\.atom\packages\atom-perforce\main.js:141:22
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\pane-container.js:145:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\workspace.js:329:33)
    at setupObservers (C:\Users\MyUser\.atom\packages\atom-perforce\main.js:140:34)
    at Object.activate (C:\Users\MyUser\.atom\packages\atom-perforce\main.js:185:17)
    at Package.module.exports.Package.activateNow (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package.js:183:20)
    at C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package.js:92:15)
    at C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package-manager.js:535:21)
    at C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package-manager.js:516:29
    at Config.module.exports.Config.transactAsync (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package-manager.js:511:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\package-manager.js:494:46)
    at C:\Users\MyUser\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-perforce, v1.7.6
highlight-selected, v0.11.2
meteor-api, v2.20.0
monokai, v0.18.0
vim-mode, v0.65.0
vim-mode-plus, v0.29.0
vim-mode-plus-move-selected-text, v0.4.1

# Dev
No dev packages
```

**Comment by maxnoel** [comment]
This issue isn't specific to atom-perforce, it's a regression in Atom 1.7.x beta :  https://github.com/atom/atom/issues/11302

(on Windows, `process.env`'s keys are no longer case-insensitive, and since there's a good chance your `%PATH%` is `Path` instead of `PATH`, boom)

**Comment by PhiLhoSoft** [comment]
Argh, now 1.7 is released, and I have the issue too!
Seriously? They released a new version which knowingly breaks existing packages?

**Comment by stefangotz** [comment]
+1

**Comment by PhiLhoSoft** [comment]
Might I risk a suggestion? Atom doesn't seem to be fixing this issue quickly.
Meanwhile, perhaps if you get an empty `PATH` environment variable, you can try and read the `Path` one? At least, it is unlikely somebody named it paTh or something...
Having this package broken is really annoying for daily dev tasks at work.
Thanks.

**Comment by unional** [comment]
It's a good idea, I almost did it, but seems like it issue is fixed and merged. Can you verify?
https://github.com/atom/atom/pull/11489

**Comment by PhiLhoSoft** [comment]
I don't know in which version of Atom it will appear. I upgraded today to 1.7.2 without improvement. But indeed, that's good news, and I suppose we just have to wait. :smile: 
Will confirm here once I see it fixed, so that you can close the issue.

**Comment by devilpig** [comment]
This issue is still valid in 1.7.2...Any idea when it will be fixed? :)

**Comment by unional** [comment]
That sucks. I don't have time to work on it these two weeks. The fix is simple. Can anyone help with a PR?

**Comment by devilpig** [comment]
Changing to Path, as PhiLhoSoft suggested seems to work as a temporary fix :) thanks for the help!

**Comment by mattsawyer77** [comment]
I have a patch up, but not a good way to test it (as in soon, and, in Windows): https://github.com/mattsawyer77/atom-perforce/commit/e93522e55baa6851ce3fc6f539a050f4ddf8909c
Would someone mind doing a quick smoke test on this? @devilpig @unional @PhiLhoSoft @lqlau @maxnoel ?

**Comment by maxnoel** [comment]
I'll give it a shot tomorrow at work. It looks like it should work.

Meanwhile the proper fix is in Atom master, but hasn't reached even 1.8.0-beta2 :(

**Comment by PhiLhoSoft** [comment]
OK, I made a quick test: edited atom-perforce.js with your changes, restarted Atom: no more error message on start up, was able to check out a file by editing it.
So you patch works for me.
Might be worth keeping in source, as they can mess up this path thing another time... :smile:

**Comment by mattsawyer77** [comment]
@PhiLhoSoft thanks for testing. and my TODO comment was not directly related to the upstream bug, but merely that I don't want to do this global state mutation at all :)

**Comment by mattsawyer77** [comment]
closed via https://github.com/mattsawyer77/atom-perforce/commit/e93522e55baa6851ce3fc6f539a050f4ddf8909c
